spring.datasource.url=jdbc:postgresql://engenharia-de-dados-grupo-b.crmuughivue0.us-east-1.rds.amazonaws.com:5432/postgres?stringtype=unspecified
spring.datasource.username=professor
spring.datasource.password=professor

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true